console.log("BIENVENIDO AL SISTEMA DE TEST UNITARIOS DE LA APLICACION ATM SSFRAMEWORK");

console.log("EJECUTE EL COMANDO NPM RUN TEST")

console.log("COLOQUE EN LA CARPETA LIBS LOS ARCHIVOS .JS DE LA CARPETA PUBLIC/LIBS/ATMJS DEL PROYECTO ATM")